language: node_js

node_js:
  - "6"

before_install: cd my-site
branches:
  only:
    - master
 
cache:
  directories:
    - node_modules
 
script:
  - npm run build.prod
 
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  
  local_dir: dist
  on:
    branch: master